name: test & build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup java & gradle
        uses: sdkman/sdkman-action@main
        id: sdkman
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
      - name: build
        run: gradle build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
